# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "YNJenkinsTestiOS.xcworkspace", scheme: "YNJenkinsTestiOS")
    upload_to_app_store
  end

before_all do
    #ENV["FASTLANE_USER"] = "1003580893@qq.com"
    #ENV["FASTLANE_PASSWORD"] = “Zhengyongneng1234”

#export FASTLANE_SESSION fastlane spaceauth -u 1003580893@qq.com
end

desc “adhoc”
  lane :adhoc do
	
    cocoapods
    
    sigh(force: true,
    adhoc: true,
    output_path: "./build"
  )
    gym(workspace: "YNJenkinsTestiOS.xcworkspace", 
        scheme: "YNJenkinsTestiOS", 
        clean: true, 
        output_directory: "./build",
        archive_path: "./build",
	build_path: "./build”,
	export_method: “ad-hoc”,
)

    pgyer(api_key: "d6f507b02419dcf52acc384516ac7292", user_key: "59f5659abf79a6316ce009133c671263")

  end
end
