# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "YNJenkinsTestiOS.xcworkspace", scheme: "YNJenkinsTestiOS")
    upload_to_app_store
  end

before_all do
    ENV["FASTLANE_USER"] = "1003580893@qq.com"
    ENV["FASTLANE_PASSWORD"] = “Zhengyongneng1234”

#export FASTLANE_SESSION fastlane spaceauth -u 1003580893@qq.com
export FASTLANE_SESSION='---\n- !ruby/object:HTTP::Cookie\n  name: DES569e5a0717aef8d4abb29a6a52964aabb\n  value: HSARMTKNSRVTWFlaOdx64zcqxaR+Yt5x6h52Obxmdnqi4hj/tQ6cpZEpeUr36pq8N/hTrn1QuiNFH13wal4Ay+PRcwRTekxl8pKp+2LMPwZwu0G+hnqsXCZbwgA92PM=SRVT\n  domain: idmsa.apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 2592000\n  created_at: 2018-01-26 17:57:54.246093000 +08:00\n  accessed_at: 2018-01-29 23:04:09.218337000 +08:00\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJTaFRfNzFOZVJvWHg0T3loTHh0Y1NnIn0.A6R0j4IEBGy6pJbI1Ooz9rNvcK8PsCZzO9B99km0DzM\n  domain: olympus.itunes.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 1800\n  created_at: &1 2018-01-29 23:04:18.734634000 +08:00\n  accessed_at: *1\n'
end

#cocoapods
desc “adhoc”
  lane :adhoc do
    
    sigh(force: true,
    adhoc: true,
    output_path: "./build"
  )
    gym(workspace: "YNJenkinsTestiOS.xcworkspace", 
        scheme: "YNJenkinsTestiOS", 
        clean: true, 
        output_directory: "./build",
        archive_path: "./build",
	build_path: "./build”,
	export_method: “ad-hoc”,
)

    pgyer(api_key: "d6f507b02419dcf52acc384516ac7292", user_key: "59f5659abf79a6316ce009133c671263")

  end
end
